version: "3"

services:
  nginx:
    build:
      dockerfile: ./app/docker/nginx.dockerfile
      context: .
    image: jonathanmdr/nginx-lb
    container_name: nginx-lb
    ports:
      - "80:80"
    networks:
      - production-network
    depends_on: 
      - "app-1"
      - "app-2"
      - "app-3"

  mongodb:
    image: mongo:latest
    container_name: mongodb  
    networks:
      - production-network

  app-1:
    build:
      dockerfile: ./app/docker/books.dockerfile
      context: .
    image: jonathanmdr/books
    container_name: books-1
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  app-2:
    build:
      dockerfile: ./app/docker/books.dockerfile
      context: .
    image: jonathanmdr/books
    container_name: books-2
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  app-3:
    build:
      dockerfile: ./app/docker/books.dockerfile
      context: .
    image: jonathanmdr/books
    container_name: books-3
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"


networks:
  production-network:
    driver: bridge