name: Docker Compose Actions Workflow
on:
  push:    
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build apps
        run: docker-compose up -d
      - name: Test apps
        run: |
          docker run --network container:books-1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
          docker run --network container:books-2 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
          docker run --network container:books-3 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/          
